In [3]:
kobis_df = pd.read_csv('./datas/kobis.csv')
kobis_df.drop(columns=['Unnamed: 0'], inplace=True)

In [32]:
from sklearn.preprocessing import LabelEncoder

In [4]:
kobis_df

         Code        Movie  Audience  Screen genres AgeRate  month  year
0    20192193           도굴   565.469    1634     범죄  청소년관람가     11  2020
1    20197121   삼진그룹 영어토익반  1257.444    1080    드라마  청소년관람가     10  2020
2    20199816           담보  1702.252     407    드라마  청소년관람가      9  2020
3    20208508  미스터트롯: 더 무비   140.594     159     공연   전체관람가     10  2020
4    20194424       소리도 없이   401.759     126     범죄  청소년관람가     10  2020
..        ...          ...       ...     ...    ...     ...    ...   ...
411  20145501         돌연변이   100.498       7    드라마  청소년관람가     10  2015
412  20157465         그놈이다  1045.218      35    스릴러  청소년관람가     10  2015
413  20157464          더 폰  1593.592       7    스릴러  청소년관람가     10  2015
414  20142855       성난 변호사  1127.747      21     범죄  청소년관람가     10  2015
415  20149961  미안해 사랑해 고마워    50.571       5    드라마  청소년관람가     10  2015

[416 rows x 8 columns]

In [7]:
import numpy as np

In [96]:
labelencoder = LabelEncoder()
kobis_df['year_cat'] = labelencoder.fit_transform(kobis_df['year'])
kobis_df.head(15)

,Code,Movie,Audience,Screen,genres,AgeRate,month,year,month_four,year_cat
0,20192193,도굴,565.469,1634,범죄,청소년관람가,11,2020,4,35
1,20197121,삼진그룹 영어토익반,1257.444,1080,드라마,청소년관람가,10,2020,4,35
2,20199816,담보,1702.252,407,드라마,청소년관람가,9,2020,3,35
3,20208508,미스터트롯: 더 무비,140.594,159,공연,전체관람가,10,2020,4,35
4,20194424,소리도 없이,401.759,126,범죄,청소년관람가,10,2020,4,35
5,20209304,다만 악에서 구하소서 파이널컷,34.205,78,액션,18세이상관람가,10,2020,4,35
6,20178401,검객,188.990,23,액션,청소년관람가,9,2020,3,35
7,20206588,극장판 미니특공대: 햄버거괴물의 습격,55.468,38,애니메이션,전체관람가,9,2020,3,35
8,20081003,박쥐,2208.279,1,공포(호러),18세이상관람가,4,2009,2,24
9,20206826,"그대, 고맙소 : 김호중 생애 첫 팬미팅 무비",100.725,53,공연,전체관람가,9,2020,3,35
10,20193666,오! 문희,350.993,20,코미디,청소년관람가,9,2020,3,35
11,20204684,브레이크 더 사일런스: 더 무비,131.693,66,다큐멘터리,전체관람가,9,2020,3,35
12,20190601,디바,107.480,6,스릴러,청소년관람가,9,2020,3,35
13,20196750,웰컴 투 X-월드,0.710,2,다큐멘터리,전체관람가,10,2020,4,35
14,20184482,국제수사,534.629,11,코미디,청소년관람가,9,2020,3,35

In [86]:
kobis_df

,Code,Movie,Audience,Screen,genres,AgeRate,month,year,month_four,year_cat
0,20192193,도굴,565.469,1634,범죄,청소년관람가,11,2020,4,35
1,20197121,삼진그룹 영어토익반,1257.444,1080,드라마,청소년관람가,10,2020,4,35
2,20199816,담보,1702.252,407,드라마,청소년관람가,9,2020,3,35
3,20208508,미스터트롯: 더 무비,140.594,159,공연,전체관람가,10,2020,4,35
4,20194424,소리도 없이,401.759,126,범죄,청소년관람가,10,2020,4,35
...,...,...,...,...,...,...,...,...,...,...
411,20145501,돌연변이,100.498,7,드라마,청소년관람가,10,2015,4,30
412,20157465,그놈이다,1045.218,35,스릴러,청소년관람가,10,2015,4,30
413,20157464,더 폰,1593.592,7,스릴러,청소년관람가,10,2015,4,30
414,20142855,성난 변호사,1127.747,21,범죄,청소년관람가,10,2015,4,30
415,20149961,미안해 사랑해 고마워,50.571,5,드라마,청소년관람가,10,2015,4,30

In [87]:
kobis_df.to_csv('./datas/kobis_movie(encode).csv', sep=',', encoding='utf-8')

In [89]:
ko = pd.read_csv("./datas/kobis.csv", index_col=[0])
ko

         Code        Movie  Audience  Screen genres AgeRate  month  year
0    20192193           도굴   565.469    1634     범죄  청소년관람가     11  2020
1    20197121   삼진그룹 영어토익반  1257.444    1080    드라마  청소년관람가     10  2020
2    20199816           담보  1702.252     407    드라마  청소년관람가      9  2020
3    20208508  미스터트롯: 더 무비   140.594     159     공연   전체관람가     10  2020
4    20194424       소리도 없이   401.759     126     범죄  청소년관람가     10  2020
..        ...          ...       ...     ...    ...     ...    ...   ...
411  20145501         돌연변이   100.498       7    드라마  청소년관람가     10  2015
412  20157465         그놈이다  1045.218      35    스릴러  청소년관람가     10  2015
413  20157464          더 폰  1593.592       7    스릴러  청소년관람가     10  2015
414  20142855       성난 변호사  1127.747      21     범죄  청소년관람가     10  2015
415  20149961  미안해 사랑해 고마워    50.571       5    드라마  청소년관람가     10  2015

[416 rows x 8 columns]

In [105]:
season = pd.cut(np.array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2]), 4, labels=[1, 2, 3, 4])
season

[1, 2, 2, 2, 3, ..., 4, 4, 4, 1, 1]
Length: 12
Categories (4, int64): [1 < 2 < 3 < 4]

In [130]:
ko['four_month'] = [(month%12 + 3)//3 for month in d]
ko

,Code,Movie,Audience,Screen,genres,AgeRate,month,year,four_month
0,20192193,도굴,565.469,1634,범죄,청소년관람가,11,2020,4
1,20197121,삼진그룹 영어토익반,1257.444,1080,드라마,청소년관람가,10,2020,4
2,20199816,담보,1702.252,407,드라마,청소년관람가,9,2020,4
3,20208508,미스터트롯: 더 무비,140.594,159,공연,전체관람가,10,2020,4
4,20194424,소리도 없이,401.759,126,범죄,청소년관람가,10,2020,4
...,...,...,...,...,...,...,...,...,...
411,20145501,돌연변이,100.498,7,드라마,청소년관람가,10,2015,4
412,20157465,그놈이다,1045.218,35,스릴러,청소년관람가,10,2015,4
413,20157464,더 폰,1593.592,7,스릴러,청소년관람가,10,2015,4
414,20142855,성난 변호사,1127.747,21,범죄,청소년관람가,10,2015,4
415,20149961,미안해 사랑해 고마워,50.571,5,드라마,청소년관람가,10,2015,4

In [131]:
labelencoder = LabelEncoder()
ko['year_cat'] = labelencoder.fit_transform(ko['year'])
ko

,Code,Movie,Audience,Screen,genres,AgeRate,month,year,four_month,year_cat
0,20192193,도굴,565.469,1634,범죄,청소년관람가,11,2020,4,35
1,20197121,삼진그룹 영어토익반,1257.444,1080,드라마,청소년관람가,10,2020,4,35
2,20199816,담보,1702.252,407,드라마,청소년관람가,9,2020,4,35
3,20208508,미스터트롯: 더 무비,140.594,159,공연,전체관람가,10,2020,4,35
4,20194424,소리도 없이,401.759,126,범죄,청소년관람가,10,2020,4,35
...,...,...,...,...,...,...,...,...,...,...
411,20145501,돌연변이,100.498,7,드라마,청소년관람가,10,2015,4,30
412,20157465,그놈이다,1045.218,35,스릴러,청소년관람가,10,2015,4,30
413,20157464,더 폰,1593.592,7,스릴러,청소년관람가,10,2015,4,30
414,20142855,성난 변호사,1127.747,21,범죄,청소년관람가,10,2015,4,30
415,20149961,미안해 사랑해 고마워,50.571,5,드라마,청소년관람가,10,2015,4,30

In [94]:
convert = [(month%12 + 3)//3 for month in range(1, 13)]
convert

[1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 1]

In [132]:
ko.to_csv('./datas/kobis_movie(encode).csv', sep=',', encoding='utf-8')

In [137]:
d1 = pd.read_csv("./datas/Rev2_kobis.csv", index_col=[0])
d1

,Code,Movie,Audience,Screen,genres,AgeRate,month,year,month_four,year_cat,마동석,황정민,정만식,박성웅,라미란,송강호,오달수,성동일,조진웅,김희원
0,20192193,도굴,565.469,1634,범죄,청소년관람가,11,2020,4,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20197121,삼진그룹 영어토익반,1257.444,1080,드라마,청소년관람가,10,2020,4,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,20199816,담보,1702.252,407,드라마,청소년관람가,9,2020,3,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,20208508,미스터트롯: 더 무비,140.594,159,공연,전체관람가,10,2020,4,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20194424,소리도 없이,401.759,126,범죄,청소년관람가,10,2020,4,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,20145501,돌연변이,100.498,7,드라마,청소년관람가,10,2015,4,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
412,20157465,그놈이다,1045.218,35,스릴러,청소년관람가,10,2015,4,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
413,20157464,더 폰,1593.592,7,스릴러,청소년관람가,10,2015,4,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
414,20142855,성난 변호사,1127.747,21,범죄,청소년관람가,10,2015,4,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
415,20149961,미안해 사랑해 고마워,50.571,5,드라마,청소년관람가,10,2015,4,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [138]:
d2 = pd.read_csv("./datas/movie_points.csv")
d2

                                                                                                movie_result
NaN   Unnamed: 0 Code     Movie       Audience Open       Screen watchGradeNm genres year month        Point
0.0   0          20192193 도굴          565469   2020-11-04 1634   12세이상관람가     범죄     2020 11            7.52
1.0   1          20197121 삼진그룹 영어토익반  1257444  2020-10-21 1080   12세이상관람가     드라마    2020 10            8.73
2.0   2          20199816 담보          1702252  2020-09-29 407    12세이상관람가     드라마    2020 9              8.9
3.0   3          20208508 미스터트롯: 더 무비 140594   2020-10-22 159    전체관람가        공연     2020 10            8.95
...                                                                                                      ...
411.0 415        20145501 돌연변이        100498   2015-10-22 7      12세이상관람가     드라마    2015 10            7.19
412.0 416        20157465 그놈이다        1045218  2015-10-28 35     15세이상관람가     스릴러    2015 10            7.61
413.0 417        20157464 더 폰         1593592  2015-10-22 7      15세이상관람가     스릴러    2015 10             7.5
414.0 418        20142855 성난 변호사      1127747  2015-10-08 21     15세이상관람가     범죄     2015 10            8.15
415.0 419        20149961 미안해 사랑해 고마워 50571    2015-10-28 5      15세이상관람가     드라마    2015 10             7.4

[417 rows x 1 columns]