- 데이터 타입
- 데이터 형변환
- 입출력

### 예제

### 1. 데이터 타입을 확인하는 함수를 사용하여 아래 변수의 데이터 타입을 확인하세요.

```
data = "python"
```

In [0]:
data = "python"
type(data)

str

### 2. 오프셋 인덱스와 split(), upper() 함수를 사용하여 아래의 문자열의 첫번째 문자를 대문자로 변경하세요.

```
data = "python science"
```

- 결과

```
result => "Python Science"
```

In [0]:
data = "python science"
result = data.split(" ")
result = result[0][0].upper() + result[0][1:] + " " + result[1][0].upper() + result[1][1:]
result

'Python Science'

### 3. 아래의 딕셔너리 데이터에서 국어와 수학점수를 더한 점수를 출력하세요.

```
dic = {"국어": 80, "수학": 90}
```

- 결과

```
result => 170
```

In [0]:
dic = {"국어": 80, "수학": 90}
result = dic["국어"] + dic["수학"]
print(result)

170

In [0]:
dic = {"국어": 80, "수학": 90}
result = list(dic.values())
result = result[0] + result[1]
print(result)

170

### 4. 아래의 리스트를 ,로 구분하는 문자열로 변경하는 코드를 작성하세요.

```
ls = ["data", "science", "python"]
```

- 결과

```
result => "data, science, python"
```

In [0]:
ls = ["data", "science", "python"]
result = ", ".join(ls)
print(result)

data, science, python

### 5. 아래의 리스트를 내림차순으로 정렬하세요.

```
ls = [3, 1, 2, 7, 4, 9]
```

- 결과

```
result => [9, 7, 4, 3, 2, 1]
```

In [0]:
ls = [3, 1, 2, 7, 4, 9]
result = ls
result.sort()
result.reverse()
print(result)

[9, 7, 4, 3, 2, 1]

### 6. 문자열을 3번 입력 받아 ,로 구분자로 문자열을 출력하세요.

- input함수를 3번 print 함수를 한번 사용하세요

In [0]:
data1 = input("insert string : ")
data2 = input("insert string : ")
data3 = input("insert string : ")
print(data1, data2, data3, sep=", ")

insert string : fast
insert string : campus
insert string : python
fast,campus,python

### 7. boolean 형변환 했는데 false인 경우는?

정답 3, 5

1. bool(" ")
1. bool(1)
1. bool(0)
1. bool([0])
1. bool({})

### 8. string format 함수를 사용하여 딕셔너리 데이터를 결과와 같이 출력하세요.

- list(dic.values()) 코드를 사용하여 딕셔너리의 value 데이터를 리스트로 변경해서 코드를 작성하세요.

```
dic = { "korean":80, "english":90 }
```

- 결과

```
result => "korean:80, english:90"
```

In [0]:
dic = { "korean":80, "english":90 }
print("{}:{}, {}:{}".format(list(dic.keys())[0], list(dic.values())[0], list(dic.keys())[1], list(dic.values())[1]))

korean:80, english:90

### 9. 아래의 리스트 데이터를 다 더하는 코드를 작성하세요.

```
ls = [[1, 2], [3, 4]]
```

- sum 함수를 사용하세요.

```
data = [1, 2, 3]
sum(data) => 6
```

In [0]:
ls = [[1, 2], [3, 4]]
result = sum(ls[0]) + sum(ls[1])
result

10

### 10. sum 함수를 이용하여 딕셔너리 데이터를 다 더한 결과를 출력하세요.

```
data = {"korean":80, "english": 70, "math": 90}
```

- 결과

```
result => 240
```

In [0]:
data = {"korean":80, "english": 70, "math": 90}
result = sum(list(data.values()))
result

240